# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BRFM.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 310)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(20, 240, 89, 25))
        self.startButton.setObjectName("startButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(130, 240, 481, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.inputDirectory = QtWidgets.QLineEdit(self.centralwidget)
        self.inputDirectory.setGeometry(QtCore.QRect(20, 40, 511, 25))
        self.inputDirectory.setObjectName("inputDirectory")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 301, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 121, 17))
        self.label_2.setObjectName("label_2")
        self.outputDirectory = QtWidgets.QLineEdit(self.centralwidget)
        self.outputDirectory.setGeometry(QtCore.QRect(20, 90, 511, 25))
        self.outputDirectory.setObjectName("outputDirectory")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 171, 17))
        self.label_3.setObjectName("label_3")
        self.filenameBox = QtWidgets.QLineEdit(self.centralwidget)
        self.filenameBox.setGeometry(QtCore.QRect(20, 140, 371, 25))
        self.filenameBox.setObjectName("filenameBox")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(410, 120, 171, 17))
        self.label_4.setObjectName("label_4")
        self.extBox = QtWidgets.QLineEdit(self.centralwidget)
        self.extBox.setGeometry(QtCore.QRect(412, 140, 201, 25))
        self.extBox.setInputMask("")
        self.extBox.setObjectName("extBox")
        self.numberOfFiles = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.numberOfFiles.setGeometry(QtCore.QRect(20, 190, 191, 26))
        self.numberOfFiles.setDecimals(0)
        self.numberOfFiles.setMaximum(1000000.0)
        self.numberOfFiles.setObjectName("numberOfFiles")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 170, 201, 17))
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setLineWidth(1)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setScaledContents(False)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.minSizeBox = QtWidgets.QLineEdit(self.centralwidget)
        self.minSizeBox.setGeometry(QtCore.QRect(230, 190, 181, 25))
        self.minSizeBox.setObjectName("minSizeBox")
        self.maxSizeBox = QtWidgets.QLineEdit(self.centralwidget)
        self.maxSizeBox.setGeometry(QtCore.QRect(430, 190, 181, 25))
        self.maxSizeBox.setObjectName("maxSizeBox")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(230, 170, 181, 17))
        self.label_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(430, 170, 131, 17))
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.inputDirectory, self.outputDirectory)
        MainWindow.setTabOrder(self.outputDirectory, self.filenameBox)
        MainWindow.setTabOrder(self.filenameBox, self.extBox)
        MainWindow.setTabOrder(self.extBox, self.numberOfFiles)
        MainWindow.setTabOrder(self.numberOfFiles, self.minSizeBox)
        MainWindow.setTabOrder(self.minSizeBox, self.maxSizeBox)
        MainWindow.setTabOrder(self.maxSizeBox, self.startButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bulk Random File Maker"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.label.setText(_translate("MainWindow", "Input File (File that contains text to fill Files)"))
        self.label_2.setText(_translate("MainWindow", "Output Directory"))
        self.label_3.setText(_translate("MainWindow", "Filename (no extensions)"))
        self.label_4.setText(_translate("MainWindow", "Extension (txt, log, etc.)"))
        self.label_5.setText(_translate("MainWindow", "# of Files you want to Create"))
        self.label_6.setText(_translate("MainWindow", "Minimum Size (KB)"))
        self.label_7.setText(_translate("MainWindow", "Maximum Size (KB)"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionClose.setText(_translate("MainWindow", "Close"))


